# docker compose build

services:

  hibuz-bash:
    image: hibuz/bash
    build:
      context: .
      tags:
        - "hibuz/bash:${UBUNTU_VERSION}"
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION}

  hibuz-zsh:
    container_name: test
    image: hibuz/zsh
    build:
      context: .
      dockerfile: Dockerfile.zsh
      tags:
        - "hibuz/zsh:${UBUNTU_VERSION}"
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION}
    env_file:
      - ./common.env
    restart: unless-stopped
    #network_mode: host
    ports:
      - 5000-5001:5000-5001
    user: ubuntu
    working_dir: /home/ubuntu
    stdin_open: true
    tty: true
    privileged: true
    environment:
      #- TZ=Asia/Seoul
      - DEFAULT_ENV_ARG
    devices:
      - /dev/snd:/dev/snd
    volumes:
      #- /dev/bus/usb:/dev/bus/usb
      - .:/code
      - hibuz-vol:/data:Z
    #entrypoint: bash
    command: -c "/code/info.sh"
    depends_on:
      - hibuz-bash
    networks:
      hibuz.com:
          aliases:
              - test.hibuz.com
volumes:
  hibuz-vol: {}

networks:
  hibuz.com:
