services:

  hadoop-base:
    image: hibuz/hadoop-base
    build:
      context: .
      tags:
        - "hibuz/hadoop-base:${UBUNTU_VERSION}"
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        DEFAULT_USER: ${DEFAULT_USER:-hadoop}
    command: -c "/info.sh"
    volumes:
      - ./info.sh:/info.sh
