# docker compose up --build

# docker compose exec spark-dev bash
# or
# docker exec -it spark bash
version: "3.9"
services:

  spark-dev:
    container_name: spark
    image: hibuz/spark-dev
    build: .
    ports:
      - 9870:9870
      - 9864:9864
      - 8088:8088
      - 9002:10002
      - 19888:19888
      - 7080:7080
      - 8080:8080
      - 8081:8081
      - 4040:4040
      - 18080:18080
    #command: yarn,hive,historyserver
    volumes:
      - spark-vol:/tmp

volumes:
  spark-vol: {}
