# docker compose build hadoop-base
# or
# docker compose up --build

version: "3.9"
services:

  hadoop-base:
    image: hibuz/hadoop-base
    build:
      context: ../
      args:
        DEFAULT_USER: ${DEFAULT_USER:-hadoop}
